### ISSUE TITLE
Create and point wiki

### ISSUE THREAD

**Issue by VonSub** [harvested-io/info_harvested.io#1]
Create a wiki for Harvested.io

- [x] have wiki running on our own capacity
- [x] make sure it is auto update
- [x] point wiki.harvested.io to the wiki
- [x] point wiki2.harveste.io to staging wiki

**Comment by PeterNashaat** [comment]
wikis deployed in our production farm 
Links :-
 
https://wiki.harvested.io/#/
https://wiki2.harvested.io/#/
auto update is working, but if  you have time we can test it
